export const INCREMENTAR   = "INCREMENTAR"
export const DISMINUIR     = "DISMINUIR"


export const GET_ALL_NOTES_INIT         = 'GET_ALL_NOTES_INIT'
export const GET_ALL_NOTES_SUCCESS      = 'GET_ALL_NOTES_SUCCESS'
export const GET_ALL_NOTES_ERROR        = 'GET_ALL_NOTES_ERROR'
export const GET_FAVORITES_NOTES_SUCCESS = 'GET_FAVORITE_NOTES_SUCCESS'

export const GET_DETAIL_NOTE_INIT       = 'GET_DETAIL_NOTE_INIT'
export const GET_DETAIL_NOTE_SUCCESS    = 'GET_DETAIL_NOTE_SUCCESS'
export const GET_DETAIL_NOTE_ERROR      = 'GET_DETAIL_NOTE_ERROR'

export const CREATE_NOTE_INIT       = 'CREATE_NOTE_INIT'
export const CREATE_NOTE_SUCCESS    = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_ERROR      = 'CREATE_NOTE_ERROR'

export const AUTO_SAVE_NOTE_INIT       = 'AUTO_SAVE_NOTE_INIT'
export const AUTO_SAVE_NOTE_SUCCESS    = 'AUTO_SAVE_NOTE_SUCCESS'
export const AUTO_SAVE_NOTE_ERROR      = 'AUTO_SAVE_NOTE_ERROR'
export const AUTO_SAVE_TO_FALSE        = "AUTO_SAVE_TO_FALSE"

export const GET_ALL_CATEGORIES_INIT       = 'GET_ALL_CATEGORIES_INIT'
export const GET_ALL_CATEGORIES_SUCCESS    = 'GET_ALL_CATEGORIES_SUCCESS'
export const GET_ALL_CATEGORIES_ERROR      = 'GET_ALL_CATEGORIES_ERROR'

export const CREATE_CATEGORY_INIT       = 'CREATE_CATEGORY_INIT'
export const CREATE_CATEGORY_SUCCESS    = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_ERROR      = 'CREATE_CATEGORY_ERROR'



export const LOGIN_INIT       = 'LOGIN_INIT'
export const LOGIN_SUCCESS    = 'LOGIN_SUCCESS'
export const LOGIN_ERROR      = 'LOGIN_ERROR'

export const REGISTRATION_INIT       = 'REGISTRATION_INIT'
export const REGISTRATION_SUCCESS    = 'REGISTRATION_SUCCESS'
export const REGISTRATION_ERROR      = 'REGISTRATION_ERROR'

export const GET_USER_INFO_DETAIL_INIT       = 'GET_USER_INFO_DETAIL_INIT'
export const GET_USER_INFO_DETAIL_SUCCESS    = 'GET_USER_INFO_DETAIL_SUCCESS'
export const GET_USER_INFO_DETAIL_ERROR      = 'GET_USER_INFO_DETAIL_ERROR'


export const GET_USER_BASIC_INFO_INIT       = 'GET_USER_BASIC_INFO_INIT'
export const GET_USER_BASIC_INFO_SUCCESS    = 'GET_USER_BASIC_INFO_SUCCESS'
export const GET_USER_BASIC_INFO_ERROR      = 'GET_USER_BASIC_INFO_ERROR'

export const UPDATE_USER_INFO_DETAIL_INIT       = 'UPDATE_USER_INFO_DETAIL_INIT'
export const UPDATE_USER_INFO_DETAIL_SUCCESS    = 'UPDATE_USER_INFO_DETAIL_SUCCESS'
export const UPDATE_USER_INFO_DETAIL_ERROR      = 'UPDATE_USER_INFO_DETAIL_ERROR'

export const GET_USER_IMAGE_INIT       = 'GET_USER_IMAGE_INIT'
export const GET_USER_IMAGE_SUCCESS    = 'GET_USER_IMAGE_SUCCESS'
export const GET_USER_IMAGE_ERROR      = 'GET_USER_IMAGE_ERROR'


export const UPDATE_USER_IMAGE_INIT       = 'UPDATE_USER_IMAGE_INIT'
export const UPDATE_USER_IMAGE_SUCCESS    = 'UPDATE_USER_IMAGE_SUCCESS'
export const UPDATE_USER_IMAGE_ERROR      = 'UPDATE_USER_IMAGE_ERROR'


export const GET_USER_ID_INIT = "GET_USER_ID_INIT"
export const GET_USER_ID_SUCCESS = "GET_USER_ID_SUCCESS"
export const GET_USER_ID_ERROR = "GET_USER_ID_ERROR"


export const CHANGE_USER_PASSWORD_INIT = "CHANGE_USER_PASSWORD_INIT"
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS"
export const CHANGE_USER_PASSWORD_ERROR = "CHANGE_USER_PASSWORD_ERROR"

export const THEME            = 'THEME'