# Generated by Django 3.2.3 on 2021-05-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_category_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
