# Generated by Django 3.2.3 on 2021-06-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210530_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
